export default {
  colors: {
    text: '#0A2A42',
    background: '#FFFFFF',
    white: '#FFFFFF',
    black: '#000000',
    dark: '#0A2A42',
    primary: {
      blue: '#175E95',
      mint: '#10EEBD',
      lightblue: '#10b0ee',
      royalblue: '#171F95'
    },
    secondary: {
      green: '#17958D',
      lightgray: '#ECF0F3',
      cloudblue: '#C5D8E8',
      skyblue: '#73A9D4',
      darkblue: '#003057',
      blueblack: '#0A2A42',
      canvas: '#EEEBE3',
    }
  },
  breakpoints: [
    "480px",
    "600px",
    "768px",
    "992px",
    "1280px",
    "1440px"
  ],
  fonts: {
    body: 'Roboto, sans-serif',
    heading: 'Barlow Condensed, sans-serif',
  },
  fontWeights: {
    "thin": 100,
    "light": 300,
    "regular": 400,
    "semi": 500,
    "medium": 600,
    "bold": 700,
    "black": 900
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  fontSizes: [
    12, 14, 16, 20, 24, 32, 48, 64,
  ],
  text: {
    default: {
      fontFamily: 'body',
      lineHeight: 'body',
      fontWeight: 'regular',
      fontSize: 2,
      color: 'dark',
    },
    h1: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'bold',
      textTransform: 'uppercase',
      fontSize: 5,
      color: 'secondary.darkblue',
    },
    h2: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'bold',
      textTransform: 'uppercase',
      fontSize: 4,
      color: 'secondary.darkblue',
    },
    h3: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'bold',
      textTransform: 'uppercase',
      fontSize: 3,
      color: 'secondary.darkblue',
    },
    h4: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'bold',
      textTransform: 'uppercase',
      fontSize: 2,
      color: 'secondary.darkblue',
    },
    h5: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'bold',
      textTransform: 'uppercase',
      fontSize: 1,
      color: 'secondary.darkblue',
    },
    h6: {
      fontFamily: 'heading',
      lineHeight: 'heading',
      fontWeight: 'bold',
      textTransform: 'uppercase',
      fontSize: 0,
      color: 'secondary.darkblue',
    },
  },
  buttons: {
    primary: {
      bg: 'transparent',
      border: '2px solid',
      borderColor: 'primary.blue',
      p: 1,
      color: 'black',
      display: 'flex',
      cursor: 'pointer',
      justifyContent: 'center',
      alignItems: 'center',
      textTransform: 'uppercase',
      fontFamily: 'body',
      fontWeight: 'bold',
      fontSize: 1,
      letterSpacing: '.5px',
      outline: 'none',
      transition: 'all .15s ease-in',
      textDecoration: 'none',
      whiteSpace: 'nowrap',
      position: 'relative',
    },
    secondary: {
      color: 'text',
      // bg: 'secondary',
    },
    navbar: {
      fontFamily: 'heading',
      color: 'dark',
      p: 1,
      fontSize: 2,
      fontWeight: 'bold',
      textTransform: 'uppercase',
      cursor: 'pointer',
      transition: '0.2s',
      '&:hover': {
        color: 'black',
        transition: '0.2s',
      }
    }
  },
  space: [
    0,
    8,
    16,
    24,
    32,
    40,
    48,
    56,
    64,
    72,
    80,
    88,
    96,
  ],
}